### ISSUE TITLE
What is the Dak Console Source?

### ISSUE THREAD

**Issue by jhess32259** [junglejim63/daiquiri-adapter#3]
I've been trying to find the protocol for the Dak serial output, ports J2/J3 on the Omnisport 2000. Is this code based on the regular serial output, or the RTD?

**Comment by junglejim63** [comment]
Joe,
Haha, good luck with that!  I asked Daktronics for the protocol, was going
to have a technology class at the high school work with me on things like
custom-made scoreboards, or remote monitoring.  It took Daktronics about 5
seconds to tell me 'No.  That is proprietary."

Note this is NOT the RTD port, just the standard serial DB9 between the
Omnisport and the console PC (can't remember the port numbers...)

I put a serial tap between the Omnisport console and the monitoring PC next
to it and deciphered as much of the protocol as I could.  This link should
work:
https://github.com/junglejim63/daiquiri-live-server/blob/master/docs/DaktronicsMessageFormat.txt.
I fully expect I got some of it wrong, but I had it working for about a
year (my kids have all graduated from being 'swimmers' to 'swammers', so I
haven't touched any of this in a few years).

I ended up connecting the serial tap (I had one of these on loan from work:
https://www.stratusengineering.com/product/ez-tap/) between the Omnisport
and the computer running the Dak console software, then I had that
connected to a Raspberry Pi.  The Pi sent all the data into a 'message
queue' (AMQP) I had loaded on a cloud server, then I had a node web server
subscribe to the console messages and create a cool live updating web page
which exactly mirrored the Dak Console.  The Serial tap is monitoring only,
so there was no risk of adulterated data.

Worked really well.  A number of the swim parents used the app on our
phones or on a big monitor in the in the 'camping' area during tournaments
- gave a live look at the meet well before the scored meet data was pushed
out from Meet Manager.  I used to use the app when I was testing touchpads
and buttons - lag time for response was about 0.5 seconds.

I ended up taking it all out when the school's cyber-security people had a
fit about a Raspberry Pi on their network...

Good luck,
Jim

**Comment by jhess32259** [comment]
Thanks for the response, Jim. Interesting that Dak has the protocol for CTS and Ares (Omega). The Dak boards even support those protocols, but they won't share their own. 

We were able to extract the code from the Atmel chip on the controller. Reverse engineering has been slow. 

JH

**Comment by junglejim63** [comment]
What protocol are you reverse engineering?  The protocol to the
scoreboards?  If you make any progress I would be interested.

**Comment by jhess32259** [comment]
We're after the standard serial output for the LED boards (J2/J3 ports). We have a timing system for swimming. We already support CTS. The Dak boards can run in CTS mode, but most of the time the teams that want to use our system do not own the boards.
